"""Markdown report generation from SlippageRecord lists."""
from __future__ import annotations

from collections import defaultdict
from datetime import datetime, timezone
from typing import Iterable

from pnl_truthteller.reconcile import SlippageRecord


def aggregate_summary(records: Iterable[SlippageRecord]) -> dict:
    """Compute aggregate metrics for a set of records.

    Paper-era records are excluded from totals but counted separately.
    """
    records = list(records)
    paper = [r for r in records if r.is_paper_era]
    live = [r for r in records if not r.is_paper_era]

    total_theoretical = sum(r.theoretical_pnl for r in live)
    total_actual = sum(r.actual_pnl for r in live)
    total_slippage = total_actual - total_theoretical
    n_dust = sum(1 for r in live if r.dust_shares_remaining > 0.5)
    total_dust = sum(r.dust_shares_remaining for r in live)

    by_reason: dict[str, dict] = defaultdict(
        lambda: {"n": 0, "theoretical": 0.0, "actual": 0.0, "slippage": 0.0}
    )
    for r in live:
        b = by_reason[r.exit_reason or "?"]
        b["n"] += 1
        b["theoretical"] += r.theoretical_pnl
        b["actual"] += r.actual_pnl
        b["slippage"] += r.slippage_usd

    return {
        "n_total": len(records),
        "n_live": len(live),
        "n_paper": len(paper),
        "total_theoretical": total_theoretical,
        "total_actual": total_actual,
        "total_slippage": total_slippage,
        "n_dust_trades": n_dust,
        "total_dust_shares": total_dust,
        "by_reason": dict(by_reason),
        "live_records": live,
    }


def build_report(records: Iterable[SlippageRecord], *, label: str | None = None) -> str:
    """Build a Markdown slippage report."""
    summary = aggregate_summary(records)
    live = summary["live_records"]
    by_reason = summary["by_reason"]

    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    pct = 0.0
    if summary["total_theoretical"]:
        pct = summary["total_slippage"] / summary["total_theoretical"] * 100

    title = f"# Slippage Report — {now}"
    if label:
        title = f"# Slippage Report — {label} — {now}"

    lines: list[str] = [
        title,
        "",
        "## TL;DR",
        f"- Closed trades total: **{summary['n_total']}** "
        f"(paper-era: {summary['n_paper']}, live: {summary['n_live']})",
        f"- Lifetime theoretical P&L (live trades only): **${summary['total_theoretical']:+.2f}**",
        f"- Lifetime actual P&L (on-chain fills): **${summary['total_actual']:+.2f}**",
        f"- **Total slippage cost: ${summary['total_slippage']:+.2f}** "
        f"({pct:+.1f}% of theoretical)",
        f"- Trades with stranded dust on-chain: **{summary['n_dust_trades']}** "
        f"(total {summary['total_dust_shares']:.1f} shares dust)",
        "",
    ]

    if by_reason:
        lines += [
            "## By exit reason",
            "",
            "| Reason | n | Theoretical | Actual | Slippage |",
            "|---|---|---|---|---|",
        ]
        for reason, b in sorted(by_reason.items(), key=lambda x: -x[1]["n"]):
            lines.append(
                f"| {reason} | {b['n']} | ${b['theoretical']:+.2f} | "
                f"${b['actual']:+.2f} | ${b['slippage']:+.2f} |"
            )
        lines.append("")

    worst = sorted(live, key=lambda r: r.slippage_usd)[:10]
    if worst:
        lines += [
            "## Worst 10 slippage events (per-trade)",
            "",
            "| Date | Market | Reason | Theor. | Actual | Slip | Dust |",
            "|---|---|---|---|---|---|---|",
        ]
        for r in worst:
            d = (r.exit_time or "")[:10]
            q = (r.question or "")[:50]
            lines.append(
                f"| {d} | {q} | {r.exit_reason} | "
                f"${r.theoretical_pnl:+.2f} | ${r.actual_pnl:+.2f} | "
                f"${r.slippage_usd:+.2f} | {r.dust_shares_remaining:.0f} sh |"
            )
        lines.append("")

    lines += [
        "## Methodology",
        "",
        "- Per-trade reconciliation: each closed trade is matched to its on-chain BUY/SELL fills.",
        "- Match window: BUYs within ±2 min of `entry_time`; SELLs from `entry_time` through `exit_time + 1h`.",
        "- Fills deduplicated by `order_id` from the CLOB raw response — eliminates double-count from sweep retries.",
        "- `actual_pnl = sum(sell_takingAmount) - sum(buy_makingAmount)` — real USDC moved on-chain.",
        "- `slippage = actual - theoretical` — negative = your fill ladder walked the book down.",
        "- Paper-era trades (no matching live BUY) are excluded from totals.",
        "",
        f"*Generated by `pnl-truthteller` at {now}.*",
    ]
    return "\n".join(lines) + "\n"
